---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "33.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    #image:
      # name: traefik
      # tag: "2.8.0"

    persistence:
      enabled: true
      name: data
      accessMode: ReadWriteOnce
      size: 64Mi
      path: /data

    logs:
      general:
        level: DEBUG
      acces:
        enabled: true

    ingressRoute:
      dashboard:
        enabled: true