apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: podinfo
spec:
  chart:
    spec:
      version: "1.15.1"
  values:
    expose:
      type: NodePort
      tls:
        auto:
          commonName: "harbor.dom.com"  
    harborAdminPassword: "admin"      
