apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: podinfo
spec:
  chart:
    spec:
      version: "1.15.1"
  values:
    expose:
      type: ingress
      tls:
        enabled: false
      ingress:
        hosts:
          core: harbor.dom.com
          notary: harbor.dom.com
        className: traefik
        annotations:
          kubernetes.io/ingress.class: "traefik"
