apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: podinfo
spec:
  chart:
    spec:
      version: "1.15.1"
  values:
    externalURL: "http://harbor.dom.com"
    expose:
      type: nodePort
      tls:
        enabled: false
    harborAdminPassword: "admin"      
